<?php

declare(strict_types=1);

namespace MarekSkopal\Etoro\Dto\Trading;

use DateTimeImmutable;

/**
 * @phpstan-type PositionType array{
 *     positionID: int,
 *     CID: int,
 *     openDateTime: string,
 *     openRate: float,
 *     instrumentID: int,
 *     isBuy: bool,
 *     leverage: int,
 *     takeProfitRate: float|null,
 *     stopLossRate: float|null,
 *     mirrorID: int,
 *     parentPositionID: int,
 *     amount: float,
 *     orderID: int,
 *     orderType: int,
 *     units: float,
 *     totalFees: float|null,
 *     initialAmountInDollars: float|null,
 *     isTslEnabled: bool,
 *     stopLossVersion: int,
 *     isSettled: bool,
 *     redeemStatusID: int,
 *     initialUnits: float|null,
 *     isPartiallyAltered: bool,
 *     unitsBaseValueDollars: float,
 *     isDiscounted: bool,
 *     openPositionActionType: int,
 *     settlementTypeID: int,
 *     isDetached: bool,
 *     openConversionRate: float,
 *     pnlVersion: int,
 *     totalExternalFees: float,
 *     totalExternalTaxes: float,
 *     isNoTakeProfit: bool,
 *     isNoStopLoss: bool,
 *     lotCount: float,
 *     pnL: float|null,
 *     closeRate: float|null,
 * }
 */
readonly class Position
{
    public function __construct(
        public int $positionId,
        public int $cid,
        public DateTimeImmutable $openDateTime,
        public float $openRate,
        public int $instrumentId,
        public bool $isBuy,
        public int $leverage,
        public ?float $takeProfitRate,
        public ?float $stopLossRate,
        public int $mirrorId,
        public int $parentPositionId,
        public float $amount,
        public int $orderId,
        public int $orderType,
        public float $units,
        public ?float $totalFees,
        public ?float $initialAmountInDollars,
        public bool $isTslEnabled,
        public int $stopLossVersion,
        public bool $isSettled,
        public int $redeemStatusId,
        public ?float $initialUnits,
        public bool $isPartiallyAltered,
        public float $unitsBaseValueDollars,
        public bool $isDiscounted,
        public int $openPositionActionType,
        public int $settlementTypeId,
        public bool $isDetached,
        public float $openConversionRate,
        public int $pnlVersion,
        public float $totalExternalFees,
        public float $totalExternalTaxes,
        public bool $isNoTakeProfit,
        public bool $isNoStopLoss,
        public float $lotCount,
        public ?float $pnL,
        public ?float $closeRate,
    ) {
    }

    /** @param PositionType $data */
    public static function fromArray(array $data): self
    {
        return new self(
            positionId: $data['positionID'],
            cid: $data['CID'],
            openDateTime: new DateTimeImmutable($data['openDateTime']),
            openRate: $data['openRate'],
            instrumentId: $data['instrumentID'],
            isBuy: $data['isBuy'],
            leverage: $data['leverage'],
            takeProfitRate: $data['takeProfitRate'] ?? null,
            stopLossRate: $data['stopLossRate'] ?? null,
            mirrorId: $data['mirrorID'],
            parentPositionId: $data['parentPositionID'],
            amount: $data['amount'],
            orderId: $data['orderID'],
            orderType: $data['orderType'],
            units: $data['units'],
            totalFees: $data['totalFees'] ?? null,
            initialAmountInDollars: $data['initialAmountInDollars'] ?? null,
            isTslEnabled: $data['isTslEnabled'],
            stopLossVersion: $data['stopLossVersion'],
            isSettled: $data['isSettled'],
            redeemStatusId: $data['redeemStatusID'],
            initialUnits: $data['initialUnits'] ?? null,
            isPartiallyAltered: $data['isPartiallyAltered'],
            unitsBaseValueDollars: $data['unitsBaseValueDollars'],
            isDiscounted: $data['isDiscounted'],
            openPositionActionType: $data['openPositionActionType'],
            settlementTypeId: $data['settlementTypeID'],
            isDetached: $data['isDetached'],
            openConversionRate: $data['openConversionRate'],
            pnlVersion: $data['pnlVersion'],
            totalExternalFees: $data['totalExternalFees'],
            totalExternalTaxes: $data['totalExternalTaxes'],
            isNoTakeProfit: $data['isNoTakeProfit'],
            isNoStopLoss: $data['isNoStopLoss'],
            lotCount: $data['lotCount'],
            pnL: $data['pnL'] ?? null,
            closeRate: $data['closeRate'] ?? null,
        );
    }
}
